### ISSUE TITLE
给所有操作配上截图，注明实际调用的方法

### ISSUE THREAD

**Issue by qinshulei** [zhongke/spacemacs_shortcut#1]
看了一下很不错。但在浏览的时候，感觉作为阅读者不太愿意一个一个的去在emacs上试，如果有截图，可能在脑子里感受一下就记住了。其次可能有人会改按键的绑定，注明调用方法，会帮助它找回准确的命令。

**Comment by zhongke** [comment]
谢谢你的宝贵建议，我也是才尝试做这样的改进，但是时间有限，第一优先级是收集常用的命令，而且是默认的快捷键。我会持续改进的，非常感谢！
